config/routes.rb
AptBrokerApp::Application.routes.draw do

  resources :users
  resources :clients
  resources :apartments
  resources :landlords

  resources :client_favorites

  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  get "/users/:id/confirm/:code", to: "users#check_code"

  root to: "session#new"

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :client_favorites, dependent: :destroy
  has_many :apartments, through: :client_favorites

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

 before_action :authenticate!

  include NeighborhoodHelper

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    user = User.find(session[:user_id])
    
    user.clients << @client

    redirect_to client_path(@client)
  end

  def index
    @clients = Client.all
    @user = User.find(session[:user_id])
  end

  def show
    @client = Client.find(params[:id])
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    @client.update(client_params)
    redirect_to user_path(@user)
  end


  def client_params
    params.require(:client).permit(:name, :bedrooms_needed, :price_limit, :phone_number, :email, :notes)
  end

  def check_login
    #binding.pry
    redirect_to login_path unless session[:user_id]
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="form">
<%= form_for(@client) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <br>
  <%= f.label :bedrooms_needed %>
  <%= f.number_field :bedrooms_needed %>
  
  <br>
  <%= f.label :price_limit %>
  <%= f.number_field :price_limit %>

  <br>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  
  <%= f.label :notes %>
  <%= f.text_field :notes %>
  <br>


  <%= f.submit %>

<% end %>
</div>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>
<%= render "form" %>

app/views/clients/index.html.erb
<% @user.clients.each do |client| %>
  <%= link_to client.name, client_path(client) %>
  <br>
<% end %>

app/views/clients/new.html.erb
<h1>Add Client</h1>
<%= render "form" %>

app/views/clients/show.html.erb
<br>
Client Info Page
<p>
Name:
<%= @client.name %>
<br>
Phone Number:
<%= @client.phone_number %>
<br>
Email:
<%= @client.email %>
<br>
Bedrooms Needed
<%= @client.bedrooms_needed %>
<br>
Price Limit
<%= @client.price_limit %>
<br>
Notes:
<%= @client.notes %>

</p>

<p>
  Favorites:
  <br>
  <% @client.client_favorites.each do |fav| %>
    <%= link_to fav.apartment.address, apartment_path(fav.apartment) %>
      status: <strong><%= fav.apartment.status %></strong>
    <%= form_tag client_favorite_path(fav), method: "delete" do %>
      <%= hidden_field_tag :client_id, @client.id %>
      <%= submit_tag("Remove from Favorites") %>
    <% end %>
    <br>
  <% end %>
</p>