config/routes.rb
AptBrokerApp::Application.routes.draw do

  resources :users
  resources :clients
  resources :apartments
  resources :landlords

  resources :client_favorites

  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  get "/users/:id/confirm/:code", to: "users#check_code"

  root to: "session#new"

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :landlord
  has_many :client_favorites, dependent: :destroy
  has_many :clients, through: :client_favorites

  # searchable do
  #   text :address, :description

  # end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :authenticate!
  before_action(:load_apartment, {only: [:show, :edit, :update, :destroy]})

  include NeighborhoodHelper


  def new
    @apartment = Apartment.new
  end

  def create
    @apartment = Apartment.new(apartment_params)
    @apartment.neighborhood = get_neighborhood(@apartment)

    @apartment.save
    redirect_to apartment_path(@apartment)
  end

  def index
    if (params[:price].to_i) > 1
      max = (params[:price].to_i)
    else
      max = 1000000
    end
    criteria = {price: (0..max), bedrooms: params[:bedrooms], neighborhood: params[:neighborhood]}
    criteria.delete_if {|k,v| v.blank?}
    attr_search_results = Apartment.where(criteria)
    attr_search_results = Apartment.all if attr_search_results.blank?

    text_search = "%#{params[:search]}%"
    text_results = Apartment.where('address like ? OR description like ?', text_search, text_search)

    #binding.pry
 
    @apartments = attr_search_results & text_results
  end

  def show
    @client_favorite = ClientFavorite.new
  end

  def edit
    @apartment = Apartment.find(params[:id])
  end

  def update
    @apartment = Apartment.find(params[:id])
    @apartment.update(apartment_params)
    redirect_to apartment_path(@apartment)
  end

  def destroy
    @apartment.destroy
    redirect_to apartments_path
  end

  def load_apartment
    @apartment = Apartment.find(params[:id])
  end

  def apartment_params
    params.require(:apartment).permit(:neighborhood, :address, :price, :lease_length, :bedrooms, :bathrooms, :description, :contact_name, :phone_number, :email, :photo_url, :landlord_id)
  end

  def check_login
    #binding.pry
    redirect_to login_path unless session[:user_id]
  end
end

app/views/apartments/_form.html.erb
<div class="form">
<%= form_for @apartment do |f| %>
  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :price %>
  <%= f.number_field :price %>


  <%= f.label :lease_length %>
  <%= f.number_field :lease_length %>

  <%= f.label :bedrooms %>
  <%= f.number_field :bedrooms %>

  <%= f.label :bathrooms %>
  <%= f.number_field :bathrooms %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :contact_name %>
  <%= f.text_field :contact_name %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :photo_url %>
  <%= f.url_field :photo_url %>

  <%= f.label :landlord_id %>
  <%= f.collection_select :landlord_id, Landlord.order(:name), :id, :name, include_blank: true %>

  <%= f.submit %>
<% end %>
</div>

app/views/apartments/edit.html.erb
<%= render "form" %>

app/views/apartments/index.html.erb
<h1>Search Apartments</h1>

<%= form_tag apartments_path, method: :get do %>

    <%= label_tag :search, "Extras" %>
    <%= text_field_tag :search %>

    <%= label_tag :price, "Price" %>
    <%= number_field_tag :price %>

    <%= label_tag :bedrooms, "Bedrooms:" %>
    <%= number_field_tag :bedrooms %>

    <%= label_tag :neighborhood, "Neighborhood" %>
    <%= text_field_tag :neighborhood %>

    <%= submit_tag "Search"%>
<% end %>
<div class="results">
<% @apartments.each do |apartment|%>
  <br>
  <%= link_to apartment.address, apartment_path(apartment.id) %>
  status: <strong><%= apartment.status %></strong>
  <br>
<% end %>

</div>

app/views/apartments/new.html.erb
<%= render "form" %>

app/views/apartments/show.html.erb
<div class="apt_show">
  <h1><%= @apartment.address %></h1>
<img src="<%= @apartment.photo_url %>" width="300px"/>


<!-- Add button to update apt status -->

<ul>
  <li>Status: <%= @apartment.status %></li>
  <li>Price: <%= @apartment.price %></li>
  <li>Lease (months:) <%= @apartment.lease_length %></li>
  <li>Bedrooms: <%= @apartment.bedrooms %></li>
  <li>Bathrooms: <%= @apartment.bathrooms %></li>
  <li>Descritpion: <%= @apartment.description %></li>
  <li>Contact Name: <%= @apartment.contact_name %></li>
  <li>Phone Number <%= @apartment.phone_number %></li>
  <li>Email: <%= @apartment.email %></li>
  <li>Landlord: <%= link_to @apartment.landlord.name, landlord_path(@apartment.landlord) %></li>
  <li>Neighborhood <%= @apartment.neighborhood %></li>
</ul>


  <%= button_to "Delete this apartment", apartment_path, method: :delete %>


<%= form_for(@client_favorite) do |f| %>
  
  <%= f.hidden_field(:apartment_id, value: @apartment.id) %> 
  
  <%= f.label :status %>
  <%= f.select :status, ["wanna see it", "seen it"] %>
  <br>
  <%= f.label :notes %>
  <%= f.text_field :notes %>
  <br>
  <%= f.label :client_id %>
  <%= f.collection_select :client_id, Client.order(:name), :id, :name, include_blank: true %>
  <br>
  <%= f.submit %>
<% end %>

</div>


  <% @apartment.client_favorites.each do |fave| %>
    <br>
    <ul class="client_faves">
    <li><%= link_to fave.client.name, client_path(fave.client) %>

    
    <%= "Status: #{fave.status}" %>
    <%= "Notes: #{fave.notes}" %></li>
    </ul>
    <br><br>
  <% end %>



<div class="map">

  <img src="http://maps.googleapis.com/maps/api/staticmap?&zoom=17&size=4500x450&maptype=hybrid&markers=markerstyles|<%= "#{@apartment.address}+nyc+ny" %>|&sensor=false">
</div>