config/routes.rb
AptBrokerApp::Application.routes.draw do

  resources :users
  resources :clients
  resources :apartments
  resources :landlords

  resources :client_favorites

  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  get "/users/:id/confirm/:code", to: "users#check_code"

  root to: "session#new"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>AptBrokerApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  

  <header>

    <p><%= link_to("Please Log In!","/login") if session[:user_id].nil? %></p>
    <% unless session[:user_id].nil?  %>
    <p><%= link_to("Log Out #{User.find_by(id: session[:user_id]).first_name}", "/session", method: "delete") %></p>
    <% end %>
<% if session[:user_id] %>
<ul class="menu">
 <li><%= link_to "Home", user_path(session[:user_id]), method: :get  %></li>
 <li><%= link_to "Add User", new_user_path, method: :get  %></li>
 <li><%= link_to "Add Landlord", new_landlord_path, method: :get  %></li>
 <li><%= link_to "Add Apartment", new_apartment_path, method: :get  %></li>
 <li><%= link_to "Search Apartments", apartments_path, method: :get  %></li>
 <li><%= link_to "Your Account", user_path(session[:user_id]), method: :get  %></li>
 <li> <%= link_to "All Clients", clients_path, method: :get  %></li>
 <li><%= link_to "Add Client", new_client_path, method: :get  %></li>
</ul>
<% end %>

  </header>

<h1 class="title">BROKIT</h1>

<%= yield %>

</body>
</html>